version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/
hooks:
  BeforeInstall:
    - location: cleanup.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: install.sh
      timeout: 300
      runas: root
    - location: cleanup.sh
      timeout: 300
      runas: root

